name: Test package against latest Vertica

# Triggers the workflow on push or pull request events
on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    services:
      vertica:
        image: vertica/vertica-ce:12.0.4-0
        ports:
          - 5433:5433
          - 5444:5444
        env:
          VERTICA_DB_NAME: docker
          VMART_ETL_SCRIPT: ''
          VMART_ETL_SQL: ''
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine pip-tools
    - name: Build package
      run: python -m build
    - name: Check
      run: python -m twine check -- dist/*.tar.gz
    - name: Extract reqs
      run: pip-compile -o requirements.txt --extra dev setup.py
    - name: Install reqs
      run: pip install -r requirements.txt
    - name: Install
      run: python setup.py install
    - name: Test Basic
      run: python -m pytest tests/functional/adapter/test_basic.py
    - name: Test Constraints
      run: python -m pytest tests/functional/adapter/constraints/test_constraints.py
    - name: Test Incremental
      run: python -m pytest tests/functional/adapter/incremental/
    - name: Test Concurrency
      run: python -m pytest tests/functional/adapter/concurrency/
    - name: Test Doc Generate
      run: python -m pytest tests/functional/adapter/test_doc_gen.py
    - name: Test Data Type Boolean
      run: python -m pytest tests/functional/adapter/test_data_types.py
    - name: Test Concat
      run: python -m pytest tests/functional/adapter/utils/test_concat.py
    - name: Test Data Type Int
      run: python -m pytest tests/functional/adapter/utils/data_type/
    - name: Test Last Relation Modified
      run: python -m pytest tests/functional/adapter/test_get_last_relation_modified.py
    - name: Test  Relation Caching
      run: python -m pytest tests/functional/adapter/test_list_relations_without_caching.py
    - name: Test Store test Failure
      run: python -m pytest tests/functional/adapter/store_test_failures_tests/test_store_test_failures.py
    - name: Test Date Spine
      run: python -m pytest tests/functional/adapter/utils/test_date_spine.py
    - name: Test DBT Show
      run: python -m pytest tests/functional/adapter/dbt-show/test_dbt_show.py
    - name: Test DBT Clone
      run: python -m pytest tests/functional/adapter/dbt_clone/
    - name: Test Seeds
      run: python -m pytest tests/functional/adapter/seeds/test_seeds.py



      




    


